### ISSUE TITLE
希望能允许音频轨道的语言为空

### ISSUE THREAD

**Issue by nlzy** [amefs/lsmash-muxer-gui#3]
1.3c 版本如果不设置音频轨道的语言，就会被默认设置成 jpn，但有些视频我不想定义音频轨道的语言。希望可以留空。

**Comment by amefs** [comment]
我为你提供了一个独立的版本，你可以试一下。在不选中任何语言的情况下，音轨语言属性留空
https://drive.google.com/file/d/0Bx7_euv6PUJ_QlFtMHNRUWtmcmc/view?usp=sharing

**Comment by nlzy** [comment]
试了一下，一切 OK。非常感谢！
